/*
Elastic Email REST API

This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target=\"_blank\" href=\"https://app.elasticemail.com/marketing/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target=\"_blank\" href=\"https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\">here</a>

API version: 4.0.0
Contact: support@elasticemail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package elasticemail

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MergeEmailPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MergeEmailPayload{}

// MergeEmailPayload struct for MergeEmailPayload
type MergeEmailPayload struct {
	MergeFile MessageAttachment `json:"MergeFile"`
	Content *EmailContent `json:"Content,omitempty"`
	Options *Options `json:"Options,omitempty"`
}

type _MergeEmailPayload MergeEmailPayload

// NewMergeEmailPayload instantiates a new MergeEmailPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMergeEmailPayload(mergeFile MessageAttachment) *MergeEmailPayload {
	this := MergeEmailPayload{}
	this.MergeFile = mergeFile
	return &this
}

// NewMergeEmailPayloadWithDefaults instantiates a new MergeEmailPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMergeEmailPayloadWithDefaults() *MergeEmailPayload {
	this := MergeEmailPayload{}
	return &this
}

// GetMergeFile returns the MergeFile field value
func (o *MergeEmailPayload) GetMergeFile() MessageAttachment {
	if o == nil {
		var ret MessageAttachment
		return ret
	}

	return o.MergeFile
}

// GetMergeFileOk returns a tuple with the MergeFile field value
// and a boolean to check if the value has been set.
func (o *MergeEmailPayload) GetMergeFileOk() (*MessageAttachment, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MergeFile, true
}

// SetMergeFile sets field value
func (o *MergeEmailPayload) SetMergeFile(v MessageAttachment) {
	o.MergeFile = v
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *MergeEmailPayload) GetContent() EmailContent {
	if o == nil || IsNil(o.Content) {
		var ret EmailContent
		return ret
	}
	return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MergeEmailPayload) GetContentOk() (*EmailContent, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *MergeEmailPayload) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given EmailContent and assigns it to the Content field.
func (o *MergeEmailPayload) SetContent(v EmailContent) {
	o.Content = &v
}

// GetOptions returns the Options field value if set, zero value otherwise.
func (o *MergeEmailPayload) GetOptions() Options {
	if o == nil || IsNil(o.Options) {
		var ret Options
		return ret
	}
	return *o.Options
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MergeEmailPayload) GetOptionsOk() (*Options, bool) {
	if o == nil || IsNil(o.Options) {
		return nil, false
	}
	return o.Options, true
}

// HasOptions returns a boolean if a field has been set.
func (o *MergeEmailPayload) HasOptions() bool {
	if o != nil && !IsNil(o.Options) {
		return true
	}

	return false
}

// SetOptions gets a reference to the given Options and assigns it to the Options field.
func (o *MergeEmailPayload) SetOptions(v Options) {
	o.Options = &v
}

func (o MergeEmailPayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MergeEmailPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["MergeFile"] = o.MergeFile
	if !IsNil(o.Content) {
		toSerialize["Content"] = o.Content
	}
	if !IsNil(o.Options) {
		toSerialize["Options"] = o.Options
	}
	return toSerialize, nil
}

func (o *MergeEmailPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"MergeFile",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMergeEmailPayload := _MergeEmailPayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMergeEmailPayload)

	if err != nil {
		return err
	}

	*o = MergeEmailPayload(varMergeEmailPayload)

	return err
}

type NullableMergeEmailPayload struct {
	value *MergeEmailPayload
	isSet bool
}

func (v NullableMergeEmailPayload) Get() *MergeEmailPayload {
	return v.value
}

func (v *NullableMergeEmailPayload) Set(val *MergeEmailPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableMergeEmailPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableMergeEmailPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMergeEmailPayload(val *MergeEmailPayload) *NullableMergeEmailPayload {
	return &NullableMergeEmailPayload{value: val, isSet: true}
}

func (v NullableMergeEmailPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMergeEmailPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


