/*
Elastic Email REST API

This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target=\"_blank\" href=\"https://app.elasticemail.com/marketing/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target=\"_blank\" href=\"https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\">here</a>

API version: 4.0.0
Contact: support@elasticemail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package elasticemail

import (
	"encoding/json"
	"fmt"
)

// SplitOptimizationType the model 'SplitOptimizationType'
type SplitOptimizationType string

// List of SplitOptimizationType
const (
	SPLITOPTIMIZATIONTYPE_OPENS SplitOptimizationType = "Opens"
	SPLITOPTIMIZATIONTYPE_CLICKS SplitOptimizationType = "Clicks"
)

// All allowed values of SplitOptimizationType enum
var AllowedSplitOptimizationTypeEnumValues = []SplitOptimizationType{
	"Opens",
	"Clicks",
}

func (v *SplitOptimizationType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SplitOptimizationType(value)
	for _, existing := range AllowedSplitOptimizationTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SplitOptimizationType", value)
}

// NewSplitOptimizationTypeFromValue returns a pointer to a valid SplitOptimizationType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSplitOptimizationTypeFromValue(v string) (*SplitOptimizationType, error) {
	ev := SplitOptimizationType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SplitOptimizationType: valid values are %v", v, AllowedSplitOptimizationTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SplitOptimizationType) IsValid() bool {
	for _, existing := range AllowedSplitOptimizationTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SplitOptimizationType value
func (v SplitOptimizationType) Ptr() *SplitOptimizationType {
	return &v
}

type NullableSplitOptimizationType struct {
	value *SplitOptimizationType
	isSet bool
}

func (v NullableSplitOptimizationType) Get() *SplitOptimizationType {
	return v.value
}

func (v *NullableSplitOptimizationType) Set(val *SplitOptimizationType) {
	v.value = val
	v.isSet = true
}

func (v NullableSplitOptimizationType) IsSet() bool {
	return v.isSet
}

func (v *NullableSplitOptimizationType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSplitOptimizationType(val *SplitOptimizationType) *NullableSplitOptimizationType {
	return &NullableSplitOptimizationType{value: val, isSet: true}
}

func (v NullableSplitOptimizationType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSplitOptimizationType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

