/*
Elastic Email REST API

This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target=\"_blank\" href=\"https://app.elasticemail.com/marketing/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target=\"_blank\" href=\"https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\">here</a>

API version: 4.0.0
Contact: support@elasticemail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package elasticemail

import (
	"encoding/json"
	"fmt"
)

// InboundRouteFilterType the model 'InboundRouteFilterType'
type InboundRouteFilterType string

// List of InboundRouteFilterType
const (
	INBOUNDROUTEFILTERTYPE_EMAIL_ADDRESS InboundRouteFilterType = "EmailAddress"
	INBOUNDROUTEFILTERTYPE_SUBJECT InboundRouteFilterType = "Subject"
)

// All allowed values of InboundRouteFilterType enum
var AllowedInboundRouteFilterTypeEnumValues = []InboundRouteFilterType{
	"EmailAddress",
	"Subject",
}

func (v *InboundRouteFilterType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := InboundRouteFilterType(value)
	for _, existing := range AllowedInboundRouteFilterTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid InboundRouteFilterType", value)
}

// NewInboundRouteFilterTypeFromValue returns a pointer to a valid InboundRouteFilterType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewInboundRouteFilterTypeFromValue(v string) (*InboundRouteFilterType, error) {
	ev := InboundRouteFilterType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for InboundRouteFilterType: valid values are %v", v, AllowedInboundRouteFilterTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v InboundRouteFilterType) IsValid() bool {
	for _, existing := range AllowedInboundRouteFilterTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to InboundRouteFilterType value
func (v InboundRouteFilterType) Ptr() *InboundRouteFilterType {
	return &v
}

type NullableInboundRouteFilterType struct {
	value *InboundRouteFilterType
	isSet bool
}

func (v NullableInboundRouteFilterType) Get() *InboundRouteFilterType {
	return v.value
}

func (v *NullableInboundRouteFilterType) Set(val *InboundRouteFilterType) {
	v.value = val
	v.isSet = true
}

func (v NullableInboundRouteFilterType) IsSet() bool {
	return v.isSet
}

func (v *NullableInboundRouteFilterType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInboundRouteFilterType(val *InboundRouteFilterType) *NullableInboundRouteFilterType {
	return &NullableInboundRouteFilterType{value: val, isSet: true}
}

func (v NullableInboundRouteFilterType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInboundRouteFilterType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

